runtime:
  distribution_strategy: 'one_device'
  mixed_precision_dtype: 'float32'
task:
  model:
      input_size: [640, 640, 3]
  train_data:
   global_batch_size: 64
   input_path: 'gs://cam2-datasets/coco/train*'
  validation_data:
    global_batch_size: 8
    input_path: 'gs://cam2-datasets/coco/val*'
  init_checkpoint: 'gs://cam2-models/maskformer_vishal_exps/resnet50_pretrained/tfmg/ckpt-62400'
  annotation_file: 'gs://cam2-datasets/annotations/instances_val2017.json'
  init_checkpoint_modules:all
  init_checkpoint:'gs://cam2-models/detr_vishal_exps/EXP02_v38/ckpt-1848'
  