# input_size=[640, 640, 3]
runtime:
  distribution_strategy: 'one_device'
  mixed_precision_dtype: 'float32'
task:
  model:
      input_size: [640, 640, 3]
  train_data:
   global_batch_size: 64
  validation_data:
    global_batch_size: 2