runtime:
  all_reduce_alg: null
  batchnorm_spatial_persistent: false
  dataset_num_private_threads: null
  default_shard_dim: -1
  distribution_strategy: mirrored
  enable_xla: false
  gpu_thread_mode: null
  loss_scale: null
  mixed_precision_dtype: null
  num_cores_per_replica: 1
  num_gpus: 0
  num_packs: 1
  per_gpu_thread_count: 0
  run_eagerly: false
  task_index: -1
  tpu: null
  tpu_enable_xla_dynamic_padder: null
  worker_hosts: null
task:
  allow_image_summary: false
  annotation_file: null
  differential_privacy_config: null
  init_checkpoint: ''
  init_checkpoint_modules: backbone
  losses:
    background_cls_weight: 0.1
    class_offset: 0
    l2_weight_decay: 0.0001
    lambda_box: 5.0
    lambda_cls: 1.0
    lambda_giou: 2.0
  model:
    backbone:
      resnet:
        bn_trainable: false
        depth_multiplier: 1.0
        model_id: 50
        replace_stem_max_pool: false
        resnetd_shortcut: false
        scale_stem: true
        se_ratio: 0.0
        stem_type: v0
        stochastic_depth_drop_rate: 0.0
      type: resnet
    backbone_endpoint_name: '5'
    hidden_size: 256
    input_size: [1333, 1333, 3]
    norm_activation:
      activation: relu
      norm_epsilon: 0.001
      norm_momentum: 0.99
      use_sync_bn: true
    num_classes: 81
    num_decoder_layers: 6
    num_encoder_layers: 6
    num_queries: 100
  name: null
  per_category_metrics: false
  train_data:
    apply_tf_data_service_before_batching: false
    block_length: 1
    cache: false
    cycle_length: null
    deterministic: null
    drop_remainder: true
    enable_shared_tf_data_service_between_parallel_trainers: false
    enable_tf_data_service: false
    global_batch_size: 64
    input_path: ''
    is_training: true
    max_num_boxes: 100
    output_size: !!python/tuple
    - 1333
    - 1333
    prefetch_buffer_size: null
    resize_scales: !!python/tuple
    - 480
    - 512
    - 544
    - 576
    - 608
    - 640
    - 672
    - 704
    - 736
    - 768
    - 800
    seed: null
    sharding: true
    shuffle_buffer_size: 1000
    tf_data_service_address: null
    tf_data_service_job_name: null
    tfds_as_supervised: false
    tfds_data_dir: ''
    tfds_name: coco/2017
    tfds_skip_decoding_feature: ''
    tfds_split: train
    trainer_id: null
  validation_data:
    apply_tf_data_service_before_batching: false
    block_length: 1
    cache: false
    cycle_length: null
    deterministic: null
    drop_remainder: false
    enable_shared_tf_data_service_between_parallel_trainers: false
    enable_tf_data_service: false
    global_batch_size: 64
    input_path: ''
    is_training: false
    max_num_boxes: 100
    output_size: !!python/tuple
    - 1333
    - 1333
    prefetch_buffer_size: null
    resize_scales: !!python/tuple
    - 480
    - 512
    - 544
    - 576
    - 608
    - 640
    - 672
    - 704
    - 736
    - 768
    - 800
    seed: null
    sharding: true
    shuffle_buffer_size: 100
    tf_data_service_address: null
    tf_data_service_job_name: null
    tfds_as_supervised: false
    tfds_data_dir: ''
    tfds_name: coco/2017
    tfds_skip_decoding_feature: ''
    tfds_split: validation
    trainer_id: null
trainer:
  allow_tpu_summary: false
  best_checkpoint_eval_metric: AP
  best_checkpoint_export_subdir: best_ckpt
  best_checkpoint_metric_comp: higher
  checkpoint_interval: 10000
  continuous_eval_timeout: 3600
  eval_tf_function: true
  eval_tf_while_loop: false
  loss_upper_bound: 1000000.0
  max_to_keep: 1
  optimizer_config:
    ema: null
    learning_rate:
      stepwise:
        boundaries: [739200]
        name: PiecewiseConstantDecay
        offset: 0
        values: [0.0001, 1.0e-05]
      type: stepwise
    optimizer:
      detr_adamw:
        amsgrad: false
        beta_1: 0.9
        beta_2: 0.999
        clipnorm: null
        clipvalue: null
        epsilon: 1.0e-07
        exclude_from_weight_decay: null
        global_clipnorm: 0.1
        gradient_clip_norm: 0.0
        include_in_weight_decay: null
        name: AdamWeightDecay
        weight_decay_rate: 0.0001
      type: detr_adamw
    warmup:
      type: null
  preemption_on_demand_checkpoint: true
  recovery_begin_steps: 0
  recovery_max_trials: 0
  steps_per_loop: 10000
  summary_interval: 10000
  train_steps: 924000
  train_tf_function: true
  train_tf_while_loop: true
  validation_interval: 10000
  validation_steps: -1
  validation_summary_subdir: validation
